### ISSUE TITLE
What about Keras' version?

### ISSUE THREAD

**Issue by TissueNam** [BraveGump/CGDL-for-Open-Set-Recognition#7]
I used Keras 2.3.1.

I received the following error message.

(CGDL) kcm@kcm-desktop:~/OSDN/CGDL-for-Open-Set-Recognition$ python lvae_train.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "lvae_train.py", line 15, in <module>
    from keras.utils import to_categorical
  File "/home/kcm/anaconda3/envs/CGDL/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/kcm/anaconda3/envs/CGDL/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/kcm/anaconda3/envs/CGDL/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/kcm/anaconda3/envs/CGDL/lib/python3.6/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/home/kcm/anaconda3/envs/CGDL/lib/python3.6/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/home/kcm/anaconda3/envs/CGDL/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/kcm/anaconda3/envs/CGDL/lib/python3.6/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/kcm/anaconda3/envs/CGDL/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/kcm/anaconda3/envs/CGDL/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 17, in <module>
    from tensorflow.core.framework import function_pb2 as tensorflow_dot_core_dot_framework_dot_function__pb2
  File "/home/kcm/anaconda3/envs/CGDL/lib/python3.6/site-packages/tensorflow/core/framework/function_pb2.py", line 463, in <module>
    __module__ = 'tensorflow.core.framework.function_pb2'
SystemError: google/protobuf/pyext/descriptor.cc:354: bad argument to internal function

**Comment by thinkershare** [comment]
There are some structural errors that make it no longer run on the new PyTorch, so you need to make some structural adjustments. you can remove 'from keras.utils import to_categorical'.  if you use keras 2.3.1, please check you pytorch version(pytorch 1.6.0+keras 2.3.1 are compatible)
